#ifndef IMAGEMEDIATORPLUGIN_GLOBAL_H
#define IMAGEMEDIATORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMAGEMEDIATORPLUGIN_LIB
# define IMAGEMEDIATORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define IMAGEMEDIATORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEMEDIATORPLUGIN_GLOBAL_H
